# Generated by Django 3.1.3 on 2023-04-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='questions',
            field=models.ManyToManyField(related_name='courses', to='onlinecourse.Question'),
        ),
    ]
